class_name CarFit
extends RefCounted
## GENERATED by Tools/fit_cars.gd - do not hand-edit.
##
## How to bring an imported car model to real-world scale and Godot axes.
## The glb files themselves are untouched downloads; this is the transform
## that makes them sit on the ground at the right size.
##
## Apply as: node.transform = Transform3D(Basis(rot).scaled(Vector3.ONE * s), off)

const ALL := {
	"supra_mk4": {
		"scale": 0.992817,
		"rot_deg": Vector3(-0.0, -180.0, 0.0),
		"offset": Vector3(-0.0000, 0.1352, 0.0109),
		"note": "MK4 A80",
		"verts": 183723,
		"textured": 14,
		"usable": true,
	},
	"silvia_s13": {
		"scale": 1.012533,
		"rot_deg": Vector3(-0.0, -180.0, 0.0),
		"offset": Vector3(0.0016, 0.0053, -0.0605),
		"note": "S13",
		"verts": 41729,
		"textured": 11,
		"usable": true,
	},
	"silvia_s15": {
		"scale": 0.005908,
		"rot_deg": Vector3(-0.0, -180.0, 0.0),
		"offset": Vector3(1.0222, -0.0079, 0.8300),
		"note": "S15",
		"verts": 282093,
		"textured": 114,
		"usable": true,
	},
	"wrx_gc8": {
		"scale": 0.251578,
		"rot_deg": Vector3(-0.0, 0.0, 0.0),
		"offset": Vector3(3.8391, 0.0192, 3.1263),
		"note": "GC8 blobeye",
		"verts": 137150,
		"textured": 57,
		"usable": true,
	},
	"evo_v": {
		"scale": 99.539343,
		"rot_deg": Vector3(-0.0, -180.0, 0.0),
		"offset": Vector3(-0.0000, 0.0225, -0.0069),
		"note": "CP9A, Evo6 body",
		"verts": 72460,
		"textured": 85,
		"usable": true,
	},
}

