extends SceneTree
## Derive the per-car fit transform for the imported glb models, and write
## assets/cars/fit.gd.
##
## Run: ./run.sh --script res://Tools/fit_cars.gd
##
## The models stay exactly as downloaded - re-exporting a 1M-vertex glTF just to
## bake a scale factor in is lossy, slow, and destroys the link back to the
## source. A uniform scale plus a rotation and a pivot is enough, and it is six
## numbers you can read and argue with.

## length_axis: which local axis the uploader put the car's length on.
## z_up: true when the uploader used Z as the up axis (Blender-style exports).
## target_length: real-world length in metres, from the published spec.
## Godot's forward is -Z, so a Z-up model needs -90 deg about X: that sends the
## model's +Y (its nose) to -Z and its +Z (its roof) to +Y. No extra yaw needed.
## The five JDM cars that are actually in the game. au_falcon and vt_commodore
## were cut: no CarDB id referenced either, and both are off-brief for a JDM
## drift game set in Manunda. au_falcon was dead weight regardless - zero
## textures across 1,026,571 verts, the largest asset in the repo at 48 MB.
## Recover them with `git checkout <rev> -- assets/cars/<name>.glb` if the
## decision is ever revisited.
const CARS := {
	"supra_mk4":    {"z_up": false, "length_axis": "z", "target_length": 4.514, "note": "MK4 A80"},
	"silvia_s13":   {"z_up": false, "length_axis": "z", "target_length": 4.525, "note": "S13"},
	"silvia_s15":   {"z_up": false, "length_axis": "z", "target_length": 4.545, "note": "S15"},
	"wrx_gc8":      {"z_up": false, "length_axis": "z", "target_length": 4.345, "note": "GC8 blobeye"},
	"evo_v":        {"z_up": false, "length_axis": "z", "target_length": 4.300, "note": "CP9A, Evo6 body"},
}

var lo := Vector3(INF, INF, INF)
var hi := Vector3(-INF, -INF, -INF)
var verts := 0
var meshes := 0
var textured := 0


func _initialize() -> void:
	var rows: Array = []
	for cid in CARS:
		var r := _fit(cid)
		if not r.is_empty():
			rows.append(r)
	_write(rows)
	quit()


func _fit(cid: String) -> Dictionary:
	var cfg: Dictionary = CARS[cid]
	var path := "res://assets/cars/%s.glb" % cid
	if not FileAccess.file_exists(path):
		print("%-14s MISSING" % cid)
		return {}

	lo = Vector3(INF, INF, INF)
	hi = Vector3(-INF, -INF, -INF)
	verts = 0
	meshes = 0
	textured = 0

	var doc := GLTFDocument.new()
	var st := GLTFState.new()
	if doc.append_from_file(path, st) != OK:
		print("%-14s LOAD FAILED" % cid)
		return {}
	var root: Node = doc.generate_scene(st)
	if root == null:
		print("%-14s NO SCENE" % cid)
		return {}
	_walk(root, Transform3D.IDENTITY)
	root.free()

	if lo.x > INF:
		print("%-14s NO MESHES" % cid)
		return {}

	var size: Vector3 = hi - lo
	var axis: String = cfg["length_axis"]
	var measured: float = size[axis]
	if measured <= 0.0:
		print("%-14s BAD AXIS" % cid)
		return {}

	# Uniform scale from length only. Scaling to width instead would shrink the
	# body, because most of these have mirrors in the bounding box and the
	# CarSpec widths do not.
	var s: float = float(cfg["target_length"]) / measured

	var basis := Basis.IDENTITY
	if cfg["z_up"]:
		basis = Basis(Vector3.RIGHT, -PI / 2.0)

	# Pivot: after the basis, drop the car so its bounding box sits on y=0 and is
	# centred in x and z. The origin is otherwise wherever the uploader left it,
	# which for the WRX was 3.79 above ground.
	#
	# The offset is in the parent's units, so it has to be scaled along with the
	# model. Computing it in the uploader's units and handing it over unscaled put
	# the Supra 39 m underground, because its source is 448 units long.
	var t := Vector3(
		-((basis * lo).x + (basis * hi).x) * 0.5,
		-(basis * lo).y,
		-((basis * lo).z + (basis * hi).z) * 0.5
	) * s

	var out_size: Vector3 = size * s
	print("%-14s scale=%.6f  verts=%-8d meshes=%-4d tex=%d/%d  -> %.2f x %.2f x %.2f m" % [
		cid, s, verts, meshes, textured, meshes,
		out_size.y, out_size.x, out_size.z])

	# A model that measures to a speck or a hangar is not usable, and CarVisual
	# falling back to the procedural box is a far better failure than an
	# invisible car. Texture count alone did not catch this: three cars were
	# fully textured while rendering 2 cm across or 3 m underground.
	var car_sized: bool = out_size.x > 1.0 and out_size.x < 2.6 \
		and out_size.y > 0.9 and out_size.y < 2.2 \
		and out_size.z > 3.0 and out_size.z < 6.0
	if textured > 0 and not car_sized:
		printerr("%-14s NOT CAR SIZED %.2f x %.2f x %.2f m - marked unusable" % [
			cid, out_size.x, out_size.y, out_size.z])
	return {
		"id": cid, "note": cfg["note"], "scale": s, "basis": basis,
		"offset": t, "verts": verts, "meshes": meshes, "textured": textured,
		"ok": textured > 0 and car_sized,
	}


func _write(rows: Array) -> void:
	var f := FileAccess.open("res://assets/cars/fit.gd", FileAccess.WRITE)
	if f == null:
		printerr("cannot write fit.gd")
		return
	f.store_line("class_name CarFit")
	f.store_line("extends RefCounted")
	f.store_line("## GENERATED by Tools/fit_cars.gd - do not hand-edit.")
	f.store_line("##")
	f.store_line("## How to bring an imported car model to real-world scale and Godot axes.")
	f.store_line("## The glb files themselves are untouched downloads; this is the transform")
	f.store_line("## that makes them sit on the ground at the right size.")
	f.store_line("##")
	f.store_line("## Apply as: node.transform = Transform3D(Basis(rot).scaled(Vector3.ONE * s), off)")
	f.store_line("")
	f.store_line("const ALL := {")
	for r in rows:
		var b: Basis = r["basis"]
		var ax: Vector3 = b.get_euler()
		f.store_line("\t\"%s\": {" % r["id"])
		f.store_line("\t\t\"scale\": %.6f," % r["scale"])
		f.store_line("\t\t\"rot_deg\": Vector3(%.1f, %.1f, %.1f)," % [rad_to_deg(ax.x), rad_to_deg(ax.y), rad_to_deg(ax.z)])
		f.store_line("\t\t\"offset\": Vector3(%.4f, %.4f, %.4f)," % [r["offset"].x, r["offset"].y, r["offset"].z])
		f.store_line("\t\t\"note\": \"%s\"," % r["note"])
		f.store_line("\t\t\"verts\": %d," % r["verts"])
		f.store_line("\t\t\"textured\": %d," % r["textured"])
		f.store_line("\t\t\"usable\": %s," % ("true" if r["ok"] else "false"))
		f.store_line("\t},")
	f.store_line("}")
	f.store_line("")
	f.close()
	print("\nwrote assets/cars/fit.gd (%d cars)" % rows.size())


## `parent_xf` is this node's own transform composed with all of its ancestors'.
## It is threaded down rather than read from `global_transform`, because the
## scene GLTFDocument builds is not in the tree here and global_transform
## therefore returns IDENTITY for every mesh. Measuring with identity bounds is
## what put the Evo and the Supra at 2 cm and the WRX 3 m underground: the glTF
## node graph carries the scale and translation that the raw mesh AABB never
## sees.
func _walk(n: Node, parent_xf: Transform3D) -> void:
	var xf: Transform3D = parent_xf * (n as Node3D).transform if n is Node3D else parent_xf
	if n is MeshInstance3D:
		var mi := n as MeshInstance3D
		var m := mi.mesh
		if m == null:
			return
		meshes += 1
		if m.get_surface_count() > 0:
			var mt := m.surface_get_material(0) as BaseMaterial3D
			if mt != null and mt.albedo_texture != null:
				textured += 1
			var arr := m.surface_get_arrays(0)
			if arr[Mesh.ARRAY_VERTEX] != null:
				verts += (arr[Mesh.ARRAY_VERTEX] as PackedVector3Array).size()
		var ab: AABB = mi.get_aabb()
		for i in 8:
			var c: Vector3 = xf * ab.get_endpoint(i)
			lo = Vector3(minf(lo.x, c.x), minf(lo.y, c.y), minf(lo.z, c.z))
			hi = Vector3(maxf(hi.x, c.x), maxf(hi.y, c.y), maxf(hi.z, c.z))
	for c in n.get_children():
		_walk(c, xf)
